# Formatting Statistics

This notebook demonstrates how to create publication-ready formatted statistics using format_statistics().

In [1]:
import pandas as pd
import numpy as np
from pyMyriad import AnalysisTree, simple_table, gt_table
from pyMyriad.tabular import format_statistics

In [2]:
# Create sample data and run analysis
np.random.seed(42)
df = pd.DataFrame(
    {
        "Gender": np.random.choice(["M", "F"], 200),
        "Country": np.random.choice(["US", "UK", "Canada"], 200),
        "Income": np.random.normal(50000, 15000, 200),
    }
)

atree = (
    AnalysisTree()
    .split_by("df.Gender")
    .split_by("df.Country")
    .analyze_by(
        mean=lambda df: np.mean(df.Income),
        sd=lambda df: np.std(df.Income),
        n=lambda df: len(df),
        ci_lower=lambda df: (
            np.mean(df.Income) - 1.96 * np.std(df.Income) / np.sqrt(len(df))
        ),
        ci_upper=lambda df: (
            np.mean(df.Income) + 1.96 * np.std(df.Income) / np.sqrt(len(df))
        ),
    )
)

result = atree.run(df)

## View Raw Statistics

First, look at the unformatted statistics.

In [3]:
print(simple_table(result).head(10))

  _Level_0 _Level_1 _Level_2 _Level_3 Statistic         Value
5   Gender        F  Country   Canada      mean  54375.460432
5                                            sd  14215.930754
5                                             n            31
5                                      ci_lower   49371.07762
5                                      ci_upper  59379.843244
7                                  UK      mean  50510.396621
7                                            sd  16970.685709
7                                             n            37
7                                      ci_lower  45042.068074
7                                      ci_upper  55978.725168

## Basic Formatting: Mean ± SD

Create a formatted string combining mean and standard deviation.

In [5]:
# Apply formatting to create "mean ± sd" statistic
format_statistics(result, inplace=True, mean_sd="{mean:.1f} ± {sd:.1f}")

# Display the new formatted statistic
print(simple_table(result).head(10))

  _Level_0 _Level_1 _Level_2 _Level_3 Statistic              Value
5   Gender        F  Country   Canada      mean       54375.460432
5                                            sd       14215.930754
5                                             n                 31
5                                      ci_lower        49371.07762
5                                      ci_upper       59379.843244
5                                       mean_sd  54375.5 ± 14215.9
7                                  UK      mean       50510.396621
7                                            sd       16970.685709
7                                             n                 37
7                                      ci_lower       45042.068074

## Format Confidence Intervals

Create formatted CI strings.

In [6]:
# Create a new result for this example
result2 = atree.run(df)

# Format confidence interval
format_statistics(result2, inplace=True, ci_95="({ci_lower:.0f}, {ci_upper:.0f})")

print(simple_table(result2).head(10))

  _Level_0 _Level_1 _Level_2 _Level_3 Statistic           Value
5   Gender        F  Country   Canada      mean    54375.460432
5                                            sd    14215.930754
5                                             n              31
5                                      ci_lower     49371.07762
5                                      ci_upper    59379.843244
5                                         ci_95  (49371, 59380)
7                                  UK      mean    50510.396621
7                                            sd    16970.685709
7                                             n              37
7                                      ci_lower    45042.068074

## Multi-Round Formatting

Apply formatting in multiple steps to build complex formatted statistics.

In [9]:
# Create a new result
result3 = atree.run(df)

# Round 1: Create mean ± SD
format_statistics(result3, inplace=True, mean_sd="{mean:.1f} ± {sd:.1f}")

# Round 2: Create CI range
format_statistics(result3, inplace=True, ci_range="({ci_lower:.0f}, {ci_upper:.0f})")

# Round 3: Combine into full summary
format_statistics(result3, inplace=True, full_summary="{mean_sd}, 95% CI: {ci_range}")

simple_table(result3).head(8)

,_Level_0,_Level_1,_Level_2,_Level_3,Statistic,Value
5,Gender,F,Country,Canada,mean,54375.460432
5,,,,,sd,14215.930754
5,,,,,n,31
5,,,,,ci_lower,49371.07762
5,,,,,ci_upper,59379.843244
5,,,,,mean_sd,54375.5 ± 14215.9
5,,,,,ci_range,"(49371, 59380)"
5,,,,,full_summary,"54375.5 ± 14215.9, 95% CI: (49371, 59380)"

## Include Sample Size in Formatting

Create formatted statistics with n (sample size).

In [10]:
# Create a new result
result4 = atree.run(df)

# Format with sample size
format_statistics(result4, inplace=True, mean_sd_n="{mean:.0f} ± {sd:.0f} (n={n})")

simple_table(result4)

   _Level_0 _Level_1 _Level_2 _Level_3  Statistic                 Value
5    Gender        F  Country   Canada       mean          54375.460432
5                                              sd          14215.930754
5                                               n                    31
5                                        ci_lower           49371.07762
5                                        ci_upper          59379.843244
5                                       mean_sd_n  54375 ± 14216 (n=31)
7                                   UK       mean          50510.396621
7                                              sd          16970.685709
7                                               n                    37
7                                        ci_lower          45042.068074
7                                        ci_upper          55978.725168
7                                       mean_sd_n  50510 ± 16971 (n=37)
9                                   US       mean          56604.408035
9                                              sd           11428.96618
9                                               n                    32
9                                        ci_lower          52644.473286
9                                        ci_upper          60564.342784
9                                       mean_sd_n  56604 ± 11429 (n=32)
13                 M            Canada       mean          46036.754102
13                                             sd          14652.701549
13                                              n                    35
13                                       ci_lower          41182.307224
13                                       ci_upper          50891.200981
13                                      mean_sd_n  46037 ± 14653 (n=35)
15                                  UK       mean          50473.140976
15                                             sd          11364.672448
15                                              n                    24
15                                       ci_lower          45926.325039
15                                       ci_upper          55019.956913
15                                      mean_sd_n  50473 ± 11365 (n=24)
17                                  US       mean           47535.36842
17                                             sd          13051.949651
17                                              n                    41
17                                       ci_lower           43540.15915
17                                       ci_upper          51530.577691
17                                      mean_sd_n  47535 ± 13052 (n=41)

## Publication-Ready Table

Create a final publication-quality table with formatted statistics.

In [11]:
# Create a new result
result = atree.run(df)

result = format_statistics(
    result, remove_original=True, formatted="{mean:.0f} ± {sd:.0f} (n={n})"
)

gt_table(result, pivot_statistics=False, by="df.Country")

GT(_tbl_data=pivot_lvl _Level_0 _Level_1  Statistic                Canada  \
0           Gender        F   ci_lower           49371.07762
1                             ci_upper          59379.843244
2                            formatted  54375 ± 14216 (n=31)
3                         M   ci_lower          41182.307224
4                             ci_upper          50891.200981
5                            formatted  46037 ± 14653 (n=35)

pivot_lvl                    UK                    US
0                  45042.068074          52644.473286
1                  55978.725168          60564.342784
2          50510 ± 16971 (n=37)  56604 ± 11429 (n=32)
3                  45926.325039           43540.15915
4                  55019.956913          51530.577691
5          50473 ± 11365 (n=24)  47535 ± 13052 (n=41)  , _body=<great_tables._gt_data.Body object at 0x11699b2f0>, _boxhead=Boxhead([ColInfo(var='_Level_0', type=<ColInfoTypeEnum.default: 1>, column_label='_Level_0', column_align='left', column_width=None), ColInfo(var='_Level_1', type=<ColInfoTypeEnum.default: 1>, column_label='_Level_1', column_align='left', column_width=None), ColInfo(var='Statistic', type=<ColInfoTypeEnum.default: 1>, column_label='Statistic', column_align='left', column_width=None), ColInfo(var='Canada', type=<ColInfoTypeEnum.default: 1>, column_label='Canada', column_align='left', column_width=None), ColInfo(var='UK', type=<ColInfoTypeEnum.default: 1>, column_label='UK', column_align='left', column_width=None), ColInfo(var='US', type=<ColInfoTypeEnum.default: 1>, column_label='US', column_align='left', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x116b04bc0>, _spanners=Spanners([SpannerInfo(spanner_id='Hierarchy', spanner_level=0, spanner_label='Hierarchy', spanner_units=None, spanner_pattern=None, vars=['_Level_0', '_Level_1'], built=None)]), _heading=Heading(title='Analysis Summary', subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x116802fc0>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x1168013d0>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x116801640>, _formats=[], _substitutions=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='12px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value='#f8f9fa'), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='left'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)